services:
  - type: web
    name: indirimani
    env: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    repo: https://github.com/ahmet5633/indirimani.git
    branch: main
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://ahmetgecgin7:DbHaijd6rNC9fsIY@ahmet.mudps.mongodb.net/indirimani?retryWrites=true&w=majority&appName=ahmet
        sync: false
    domains:
      - indirimani.onrender.com
    sslCert: managed
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains; preload
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: redirect
        source: /*
        destination: https://indirimani.onrender.com/:splat
        statusCode: 301 